export class OrgMeasureInfo {
  id: any;
  numeratorValue: any;
  denominatorValue: any;
  rpDate: any;
  genderMaleNum: any;
  genderMaleDen: any;
  genderFemaleNum: any;
  genderFemaleDen: any;
  age1844Num: any;
  age1844Den: any;
  age4564Num: any;
  age4564Den: any;
  ageOver65Num: any;
  ageOver65Den: any;
  ethnicityHispanicLatinoNum: any;
  ethnicityHispanicLatinoDen: any;
  ethnicityNotHispanicLatinoNum: any;
  ethnicityNotHispanicLatinoDen: any;
  raceAfricanAmericanNum: any;
  raceAfricanAmericanDen: any;
  raceAmericanIndianNum: any;
  raceAmericanIndianDen: any;
  raceAsianNum: any;
  raceAsianDen: any;
  raceNativeHawaiianNum: any;
  raceNativeHawaiianDen: any;
  raceWhiteNum: any;
  raceWhiteDen: any;
  raceOtherNum: any;
  raceOtherDen: any;
  reportPeriodYear: any;
  organizationId: any;
  measureId: any;
  userId: any;


  constructor(id: any, numeratorValue: any, denominatorValue: any, rpDate: Date, genderMaleNum: any, genderMaleDen: any, genderFemaleNum: any, genderFemaleDen: any, age1844Num: any, age1844Den: any, age4564Num: any, age4564Den: any, ageOver65Num: any, ageOver65Den: any, ethnicityHispanicLatinoNum: any, ethnicityHispanicLatinoDen: any, ethnicityNotHispanicLatinoNum: any, ethnicityNotHispanicLatinoDen: any, raceAfricanAmericanNum: any, raceAfricanAmericanDen: any, raceAmericanIndianNum: any, raceAmericanIndianDen: any, raceAsianNum: any, raceAsianDen: any, raceNativeHawaiianNum: any, raceNativeHawaiianDen: any, raceWhiteNum: any, raceWhiteDen: any, raceOtherNum: any, raceOtherDen: any, reportPeriodYear: any, organizationId: any, measureId: any, userId: any) {
    this.id = id;
    this.numeratorValue = numeratorValue;
    this.denominatorValue = denominatorValue;
    this.rpDate = rpDate;
    this.genderMaleNum = genderMaleNum;
    this.genderMaleDen = genderMaleDen;
    this.genderFemaleNum = genderFemaleNum;
    this.genderFemaleDen = genderFemaleDen;
    this.age1844Num = age1844Num;
    this.age1844Den = age1844Den;
    this.age4564Num = age4564Num;
    this.age4564Den = age4564Den;
    this.ageOver65Num = ageOver65Num;
    this.ageOver65Den = ageOver65Den;
    this.ethnicityHispanicLatinoNum = ethnicityHispanicLatinoNum;
    this.ethnicityHispanicLatinoDen = ethnicityHispanicLatinoDen;
    this.ethnicityNotHispanicLatinoNum = ethnicityNotHispanicLatinoNum;
    this.ethnicityNotHispanicLatinoDen = ethnicityNotHispanicLatinoDen;
    this.raceAfricanAmericanNum = raceAfricanAmericanNum;
    this.raceAfricanAmericanDen = raceAfricanAmericanDen;
    this.raceAmericanIndianNum = raceAmericanIndianNum;
    this.raceAmericanIndianDen = raceAmericanIndianDen;
    this.raceAsianNum = raceAsianNum;
    this.raceAsianDen = raceAsianDen;
    this.raceNativeHawaiianNum = raceNativeHawaiianNum;
    this.raceNativeHawaiianDen = raceNativeHawaiianDen;
    this.raceWhiteNum = raceWhiteNum;
    this.raceWhiteDen = raceWhiteDen;
    this.raceOtherNum = raceOtherNum;
    this.raceOtherDen = raceOtherDen;
    this.reportPeriodYear = reportPeriodYear;
    this.organizationId = organizationId;
    this.measureId = measureId;
    this.userId = userId;
  }
}
